// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zvitfplilnkhbclgrtru.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp2aXRmcGxpbG5raGJjbGdydHJ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzk3ODM4ODIsImV4cCI6MjA5NTM1OTg4Mn0.YnAtKdn-RL2dgHQD7sNzS2JC1pmqUVyOvfK7TVYVoxY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});